###
GET http://localhost:8080/users
Authorization: Bearer {token from the login end point}


###
sample request
curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InhpbmdndW8uY2hlbkBhcmFiaWRvcHNpcy5vcmciLCJ1c2VySWQiOjEsIm5hbWUiOiJYaW5nZ3VvIiwiaWF0IjoxNjY1MTgzMjQ0LCJleHAiOjE2NjUxODUwNDR9.HHO1m351NKLSGYAMgOhed-fg7mBF-9ZCtIk9Huud3mQ" http://localhost:8080/users

###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "t@g.com",
    "password": "12345",
    "name": "t"
}

###
sample request
curl -d "email=xingguo.chen@arabidopsis.org&password=techteam123&name=Xingguo" -X POST http://localhost:8080/auth/signup

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "t@g.com",
    "password": "12345"
}

###
sample request
curl -d "email=xingguo.chen@arabidopsis.org&password=techteam123" -X POST http://localhost:8080/auth/login

###
#### Need to connect to production db otherwise no project stats available
#### Add `AND published_on <= 1650648267` to project query to match dev db
GET http://localhost:8080/public/projects/data_dump
GET http://localhost:8080/public/projects/project_list_dump
sample request
curl http://localhost:8080/public/projects/data_dump
curl http://localhost:8080/public/projects/project_list_dump

###
GET http://localhost:8080/home/project/:projectId/matrix
sample request
curl http://localhost:8080/home/project/777/matrix

GET http://localhost:8080/public/projects/authors_projects

###
# Test addCharacter API with character states creation
# This should now return character with states in the response
POST http://localhost:8080/projects/1/matrices/1/edit/addCharacter
Content-Type: application/json
Authorization: Bearer {token from the login end point}

{
    "name": "Test Character",
    "charType": "C",
    "index": null
}

# Expected response should include:
# {
#   "ok": true,
#   "character": {
#     "id": 123,
#     "n": "Test Character",
#     "r": 1,
#     "t": 1,
#     "uid": 1,
#     "last_changed_on": 1234567890,
#     "s": [
#       { "id": 456, "r": 0, "n": "New State I" },
#       { "id": 457, "r": 1, "n": "New State II" }
#     ]
#   }
# }