###
GET http://localhost:8080/users
Authorization: Bearer {token from the login end point}


###
sample request
curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InhpbmdndW8uY2hlbkBhcmFiaWRvcHNpcy5vcmciLCJ1c2VySWQiOjEsIm5hbWUiOiJYaW5nZ3VvIiwiaWF0IjoxNjY1MTgzMjQ0LCJleHAiOjE2NjUxODUwNDR9.HHO1m351NKLSGYAMgOhed-fg7mBF-9ZCtIk9Huud3mQ" http://localhost:8080/users

###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "t@g.com",
    "password": "12345",
    "name": "t"
}

###
sample request
curl -d "email=xingguo.chen@arabidopsis.org&password=techteam123&name=Xingguo" -X POST http://localhost:8080/auth/signup

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "t@g.com",
    "password": "12345"
}

###
sample request
curl -d "email=xingguo.chen@arabidopsis.org&password=techteam123" -X POST http://localhost:8080/auth/login

###
GET http://localhost:8080/projects/data_dump
sample request
curl http://localhost:8080/projects/data_dump

###
GET http://localhost:8080/home/project/:projectId/matrix
sample request
curl http://localhost:8080/home/project/777/matrix