export const CELL_BATCH_TYPES = {
  MEDIA_VIEW_AUTOMATION: 0,
  MEDIA_BATCH_ADD: 1,
  MEDIA_BATCH_DELETE: 2,
  MEDIA_BATCH_SET_SCORE: 3,
  ADD_CELL_CITATION: 4,
  CELL_BATCH_NOTES: 5,
  COPY_SCORES: 6
}
